name: twitter_api
version: 1.0.1
homepage: https://github.com/stefanuros/dartTwitterAPI
description: An easy way to authenticate and make requests to the Twitter API.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.4
  crypto: ^3.0.1
